name: Build NDS ROM

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y wget xz-utils

          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x install-devkitpro-pacman
          sudo ./install-devkitpro-pacman

          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S --noconfirm devkitARM libnds

      - name: Check libnds
        run: |
          ls /opt/devkitpro/libnds

      - name: Build
        env:
          DEVKITPRO: /opt/devkitpro
          DEVKITARM: /opt/devkitpro/devkitARM
        run: |
          ls /opt/devkitpro/libnds
          make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: nds-rom
          path: "*.nds"
